import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },

  hero: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 44,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  /** Worker — compact header (year badges sit below) */
  heroWorker: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  /** Manager team-only — minimal height */
  heroTeam: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 12,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  heroTeamTitle: { fontSize: 17, fontWeight: '900', color: '#FFF', marginBottom: 2 },
  heroTeamSub: { fontSize: 11, lineHeight: 15, color: 'rgba(255,255,255,0.82)', fontWeight: '600' },
  yearBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginHorizontal: 14,
    marginTop: 10,
    marginBottom: 2,
  },
  yearBadge: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    minWidth: 64,
    alignItems: 'center',
    marginEnd: 8,
  },
  yearBadgeText: { fontSize: 13, fontWeight: '800' },
  heroRow: { flexDirection: 'row', alignItems: 'flex-start' },
  heroEyebrow: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: 'rgba(255,255,255,0.72)',
    marginBottom: 4,
  },
  heroTitle: { fontSize: 21, fontWeight: '900', color: '#FFF', marginBottom: 2 },
  heroSubtitle: { fontSize: 12, lineHeight: 16, color: 'rgba(255,255,255,0.86)' },
  yearChip: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.32)',
    backgroundColor: 'rgba(255,255,255,0.14)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignItems: 'center',
    marginStart: 10,
  },
  yearChipLabel: { fontSize: 9, textTransform: 'uppercase', letterSpacing: 0.9, color: 'rgba(255,255,255,0.7)' },
  yearChipValue: { fontSize: 14, fontWeight: '800', marginTop: 1, color: '#FFF' },

  heroCard: {
    marginHorizontal: 14,
    padding: 14,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
  },
  heroCardRow: { flexDirection: 'row', alignItems: 'center' },
  heroCardSide: { flex: 1, marginStart: 14 },
  heroCardLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  heroCardValue: { fontSize: 36, fontWeight: '900', marginTop: 2 },
  heroCardSplit: { flexDirection: 'row', marginTop: 10 },
  heroCardSplitDivider: { width: StyleSheet.hairlineWidth, marginHorizontal: 8 },
  heroSplitCell: { flex: 1 },
  heroSplitValue: { fontSize: 18, fontWeight: '900' },
  heroSplitLabel: { fontSize: 11, fontWeight: '600', marginTop: 2, textTransform: 'uppercase', letterSpacing: 0.6 },

  /** 2×2 status grid — equal width cells, accent bar, no emoji */
  pillStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  pill: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'stretch',
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    marginBottom: 10,
    overflow: 'hidden',
    minHeight: 62,
  },
  pillBar: { width: 4 },
  pillBody: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  pillLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  pillValue: { fontSize: 20, fontWeight: '900', marginTop: 4 },

  card: {
    marginHorizontal: 14,
    marginTop: 14,
    padding: 16,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
  },

  sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
  sectionAccentBar: {
    width: 4,
    height: 24,
    borderRadius: 4,
    marginEnd: 10,
  },
  sectionIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginEnd: 10,
  },
  sectionIcon: { fontSize: 16 },
  sectionTitle: { fontSize: 15, fontWeight: '800' },
  sectionSubtitle: { fontSize: 11, fontWeight: '600', marginTop: 1 },
  sectionAction: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999 },
  sectionActionText: { fontSize: 12, fontWeight: '800' },

  legendRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 10 },
  legendItem: { flexDirection: 'row', alignItems: 'center', marginHorizontal: 10 },
  legendSwatch: { width: 12, height: 12, borderRadius: 4, marginEnd: 6 },
  legendLabel: { fontSize: 12, fontWeight: '600' },

  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -5,
  },
  metricTouch: { width: '50%', padding: 5 },
  metricCard: {
    flexDirection: 'row',
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    minHeight: 84,
  },
  metricAccent: { width: 4 },
  metricBody: { flex: 1, padding: 12 },
  metricIcon: { fontSize: 16, marginBottom: 4 },
  metricValue: { fontSize: 22, fontWeight: '900', marginBottom: 2 },
  metricLabel: { fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },

  leaveRow: { paddingVertical: 12 },
  leaveHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  leaveName: { fontSize: 13, fontWeight: '700', flex: 1, marginEnd: 8 },
  leaveBadge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 999, borderWidth: StyleSheet.hairlineWidth },
  leaveBadgeText: { fontSize: 12, fontWeight: '800' },
  leaveTrack: { height: 8, borderRadius: 4, overflow: 'hidden' },
  leaveFill: { height: '100%', borderRadius: 4 },
  leaveFoot: { fontSize: 11, marginTop: 6 },

  taskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  taskAvatar: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
    marginEnd: 12,
  },
  taskAvatarText: { fontSize: 16, fontWeight: '900' },
  taskTitle: { fontSize: 13, fontWeight: '700' },
  taskMeta: { fontSize: 11, marginTop: 2, fontWeight: '600' },
  taskPct: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    marginStart: 8,
  },
  taskPctText: { fontSize: 12, fontWeight: '900' },

  emptyWrap: { alignItems: 'center', paddingVertical: 16, paddingHorizontal: 8, marginBottom: 4 },
  emptyEmoji: { fontSize: 28, marginBottom: 4 },
  emptyText: { fontSize: 12, textAlign: 'center', fontWeight: '600', lineHeight: 17 },

  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  modalSheet: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '60%',
  },
  modalHandle: { width: 40, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 12 },
  modalTitle: { fontSize: 16, fontWeight: '800', marginBottom: 8 },
  modalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  modalRowText: { fontSize: 16, fontWeight: '600' },
  modalCheck: { fontSize: 18, fontWeight: '800' },

  /** Team roster — full-width rows (replaces horizontal tiles) */
  teamListDivider: {
    height: StyleSheet.hairlineWidth,
    marginVertical: 0,
  },
  teamRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    gap: 12,
  },
  teamAvatar: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  teamAvatarText: { fontSize: 17, fontWeight: '900' },
  teamRowMiddle: { flex: 1, minWidth: 0 },
  teamRowName: { fontSize: 15, fontWeight: '800' },
  teamRowTitle: { fontSize: 12, fontWeight: '600', marginTop: 3, opacity: 0.75 },
  teamRowLevelPill: {
    alignSelf: 'flex-start',
    marginTop: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  teamRowLevelText: { fontSize: 10, fontWeight: '800', letterSpacing: 0.3 },
  teamRowRight: { alignItems: 'flex-end', minWidth: 64 },
  teamRowPerfBig: { fontSize: 22, fontWeight: '900' },
  teamRowPerfHint: { fontSize: 10, fontWeight: '700', marginTop: 4, opacity: 0.55 },
  teamHubBanner: {
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  teamHubBannerText: { fontSize: 11, fontWeight: '600', lineHeight: 16 },
  /** Horizontal reporting line — profile photos + swipe for long teams */
  teamStripScroll: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 4,
    paddingEnd: 4,
  },
  teamStripChip: {
    width: 76,
    alignItems: 'center',
    marginEnd: 10,
  },
  teamStripName: {
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 13,
    maxWidth: 76,
  },
  teamStripPct: {
    fontSize: 11,
    fontWeight: '900',
    marginTop: 3,
  },
  teamStripHint: {
    fontSize: 10,
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
    opacity: 0.65,
  },

  /** Top 3 team performers (by GetPerformance %, then assigned volume) */
  topPerfRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    gap: 10,
  },
  topPerfRankBadge: {
    width: 28,
    height: 28,
    borderRadius: 9,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topPerfRankText: { fontSize: 14, fontWeight: '900' },
  topPerfMiddle: { flex: 1, minWidth: 0 },
  topPerfName: { fontSize: 14, fontWeight: '800' },
  topPerfTitle: { fontSize: 11, fontWeight: '600', marginTop: 2, opacity: 0.85 },
  topPerfRight: { alignItems: 'flex-end', minWidth: 56 },
  topPerfClosed: { fontSize: 20, fontWeight: '900' },
  topPerfClosedLabel: { fontSize: 9, fontWeight: '700', marginTop: 1, textTransform: 'uppercase', letterSpacing: 0.4 },
  topPerfPctSmall: { fontSize: 11, fontWeight: '700', marginTop: 4 },
});
