import type { AppColors } from './colors';
import { lightColors } from './colors';
import type { ColorPaletteId } from '../settings/themePreferencesTypes';

/** SCAD “vibrant” — same as legacy facelift tokens (demo / management). */
export const paletteScadVibrant: AppColors = { ...lightColors };

/**
 * SCAD Gov: same token map as original SCAD, but light page + light hero (no dark navy header).
 * Pairs with classic home layout; uses professional / line-icon skin in `themeSkins`.
 */
export const paletteScadGov: AppColors = {
  ...lightColors,
  primary: '#1F6FCC',
  primaryDark: '#1857A3',
  primaryLight: '#E3EEF8',
  primarySoft: 'rgba(31, 111, 204, 0.1)',
  secondary: '#0A2D52',
  background: '#F2F4F8',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  cardTint: '#F4F7FB',
  greyCard: '#E1E6ED',
  stripe: '#F6F7FA',
  text: '#0A1F35',
  textSecondary: '#5C6B7A',
  textMuted: '#8A96A3',
  border: '#D6DEE8',
  borderLight: '#DFE6ED',
  divider: '#E6EBF0',
  navBar: '#FFFFFF',
  tabBar: '#FFFFFF',
  tabBarInactive: '#6B7C8A',
  statusBar: 'dark-content' as const,
  homeHeroBackground: '#E6EEF6',
  homeHeroText: '#0A1F35',
  homeHeroTextMuted: '#4A5F73',
  homeHeroSubtle: 'rgba(31, 111, 204, 0.1)',
  homeHeroBorder: 'rgba(10, 45, 90, 0.12)',
  homeStatusBar: 'dark-content' as const,
  homeDecor1: 'rgba(31, 111, 204, 0.07)',
  homeDecor2: 'rgba(10, 32, 58, 0.04)',
  profileMeta: '#F1F4F8',
  profileMetaText: '#0A1F35',
  profileMetaBorder: '#D6DEE8',
  stackHeaderBackground: '#E6EEF6',
  stackHeaderText: '#0A1F35',
  stackHeaderTint: '#1F6FCC',
  stackStatusBar: 'dark-content' as const,
};

/**
 * Neutral “eServices” list: very light grey field, white cards, quiet text, dusty accent.
 */
export const paletteGovMinimal: AppColors = {
  ...lightColors,
  primary: '#8B3A3A',
  primaryDark: '#6E2F2F',
  primaryLight: '#F4F2F2',
  primarySoft: 'rgba(139, 58, 58, 0.1)',
  secondary: '#1E293B',
  success: '#3D7A6E',
  successSoft: '#2F6A5C',
  danger: '#B45353',
  dangerSoft: '#C45C5C',
  warning: '#B8954A',
  warningSoft: '#A9843F',
  info: '#5B7A8F',
  background: '#F5F5F5',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  cardTint: '#FAFAFA',
  greyCard: '#ECEEEF',
  stripe: '#F9F9F9',
  text: '#111827',
  textSecondary: '#64748B',
  textMuted: '#94A3B8',
  border: '#E2E8F0',
  borderLight: '#E8EDF2',
  divider: '#ECEFF2',
  navBar: '#FFFFFF',
  tabBar: '#FFFFFF',
  tabBarInactive: '#94A3B8',
  notification: '#B45353',
  inputBorder: '#E2E8F0',
  tableHeader: '#F1F3F4',
  badgeNavy: '#1E293B',
  profileMeta: '#F8F9FA',
  profileMetaText: '#0F172A',
  profileMetaBorder: '#E2E8F0',
  stepConnector: '#CBD5E1',
  stepGreen: '#2F6A5C',
  stepOrange: '#B8954A',
  stepRed: '#B45353',
  statusBar: 'dark-content',
  homeHeroBackground: '#FFFFFF',
  homeHeroText: '#0F172A',
  homeHeroTextMuted: '#64748B',
  homeHeroSubtle: '#F1F5F9',
  homeHeroBorder: '#E2E8F0',
  homeStatusBar: 'dark-content',
  homeDecor1: 'rgba(15, 23, 42, 0.05)',
  homeDecor2: 'rgba(15, 23, 42, 0.03)',
  stackHeaderBackground: '#FFFFFF',
  stackHeaderText: '#111827',
  stackHeaderTint: '#8B3A3A',
  stackStatusBar: 'dark-content' as const,
};

/**
 * Soft cool grey, restrained red for key actions (inbox / tabs in reference).
 */
export const paletteGovSoft: AppColors = {
  ...lightColors,
  primary: '#B83B32',
  primaryDark: '#9A2F28',
  primaryLight: '#FEF2F2',
  primarySoft: 'rgba(184, 59, 50, 0.1)',
  secondary: '#0F172A',
  success: '#0F766E',
  successSoft: '#0D9488',
  danger: '#C23B32',
  dangerSoft: '#DC2626',
  warning: '#C27803',
  warningSoft: '#D97706',
  info: '#0369A1',
  background: '#F0F2F5',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  cardTint: '#F8FAFC',
  greyCard: '#E6E8EC',
  stripe: '#F4F6F8',
  text: '#0F172A',
  textSecondary: '#64748B',
  textMuted: '#94A3B8',
  border: '#E0E4EA',
  borderLight: '#E8EBF0',
  divider: '#E8ECF0',
  navBar: '#FFFFFF',
  tabBar: '#FFFFFF',
  tabBarInactive: '#7C8A9E',
  notification: '#B83B32',
  inputBorder: '#D9DEE6',
  tableHeader: '#F0F4F8',
  badgeNavy: '#0F172A',
  profileMeta: '#F1F5F9',
  profileMetaText: '#0F172A',
  profileMetaBorder: '#E0E4EA',
  stepConnector: '#B8C3D0',
  stepGreen: '#0D9488',
  stepOrange: '#D97706',
  stepRed: '#B83B32',
  statusBar: 'dark-content',
  homeHeroBackground: '#FFFFFF',
  homeHeroText: '#0F172A',
  homeHeroTextMuted: '#64748B',
  homeHeroSubtle: '#EEF2F6',
  homeHeroBorder: '#DDE2EA',
  homeStatusBar: 'dark-content',
  homeDecor1: 'rgba(15, 23, 42, 0.05)',
  homeDecor2: 'rgba(184, 59, 50, 0.04)',
  stackHeaderBackground: '#FFFFFF',
  stackHeaderText: '#0F172A',
  stackHeaderTint: '#B83B32',
  stackStatusBar: 'dark-content' as const,
};

/**
 * Abu Dhabi–style: deep blues, very light background, low-chroma UI.
 */
export const paletteGovAbuDhabi: AppColors = {
  ...lightColors,
  primary: '#0B5A9E',
  primaryDark: '#084A82',
  primaryLight: '#E3F0FA',
  primarySoft: 'rgba(11, 90, 158, 0.1)',
  secondary: '#043157',
  success: '#0F6B5C',
  successSoft: '#0B5C4E',
  danger: '#B84040',
  dangerSoft: '#C94A4A',
  warning: '#9A7A1E',
  warningSoft: '#B38F24',
  info: '#0B5A9E',
  background: '#F0F2F4',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  cardTint: '#F3F6FA',
  greyCard: '#E0E4EA',
  stripe: '#F5F7F9',
  text: '#0A1628',
  textSecondary: '#4A667A',
  textMuted: '#7A8F9E',
  border: '#D5DCE4',
  borderLight: '#DFE5EC',
  divider: '#E1E6EC',
  navBar: '#FFFFFF',
  tabBar: '#FFFFFF',
  tabBarInactive: '#5F7383',
  notification: '#A63C3C',
  inputBorder: '#D0D7DF',
  tableHeader: '#E8F0F8',
  badgeNavy: '#043157',
  profileMeta: '#EEF2F6',
  profileMetaText: '#0A1628',
  profileMetaBorder: '#D0D7DF',
  stepConnector: '#8FA9BC',
  stepGreen: '#0B5C4E',
  stepOrange: '#B38F24',
  stepRed: '#B84040',
  statusBar: 'dark-content',
  homeHeroBackground: '#E8F0F8',
  homeHeroText: '#043157',
  homeHeroTextMuted: '#3D5A73',
  homeHeroSubtle: 'rgba(11, 90, 158, 0.08)',
  homeHeroBorder: 'rgba(4, 49, 87, 0.12)',
  homeStatusBar: 'dark-content',
  homeDecor1: 'rgba(11, 90, 158, 0.08)',
  homeDecor2: 'rgba(4, 49, 87, 0.04)',
  stackHeaderBackground: '#E8F0F8',
  stackHeaderText: '#043157',
  stackHeaderTint: '#0B5A9E',
  stackStatusBar: 'dark-content' as const,
};

const byId: Record<ColorPaletteId, AppColors> = {
  scadVibrant: paletteScadVibrant,
  govSoft: paletteGovSoft,
  govAbuDhabi: paletteGovAbuDhabi,
};

export function getLightPalette(id: ColorPaletteId): AppColors {
  return byId[id] ?? paletteScadVibrant;
}
