package com.mazhar1785.smartscadmobile

import android.app.Application
import android.content.res.Configuration

import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.react.modules.network.OkHttpClientProvider
import com.facebook.react.soloader.OpenSourceMergedSoMapping
import com.facebook.soloader.SoLoader

import expo.modules.ApplicationLifecycleDispatcher
import expo.modules.ExpoReactHostFactory

// SDK 55 / RN 0.83 entry point.
//
// SDK 53+ removed `expo.modules.ReactNativeHostWrapper`. Expo modules are now
// wired in via `ExpoReactHostFactory.getDefaultReactHost(...)` for the New
// Architecture host, while the legacy `reactNativeHost` is kept as a plain
// `DefaultReactNativeHost` (Expo modules autolink themselves into the package
// list via the `expo` package generated by the autolinking gradle plugin).
//
// We additionally inject the SmartSCAD UAT OkHttp factory so corporate-CA
// TLS hostnames don't fail in release builds (see SmartScadUnsafeOkHttpClientFactory.kt).
class MainApplication : Application(), ReactApplication {

  override val reactNativeHost: ReactNativeHost =
    object : DefaultReactNativeHost(this) {
      override fun getPackages(): List<ReactPackage> {
        val packages = PackageList(this).packages
        // Add any non-autolinked packages here.
        return packages
      }

      override fun getJSMainModuleName(): String = ".expo/.virtual-metro-entry"

      override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

      override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
      override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
    }

  override val reactHost: ReactHost
    get() = ExpoReactHostFactory.getDefaultReactHost(
      applicationContext,
      PackageList(this).packages,
      useDevSupport = BuildConfig.DEBUG
    )

  override fun onCreate() {
    super.onCreate()
    SoLoader.init(this, OpenSourceMergedSoMapping)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      load()
    }
    OkHttpClientProvider.setOkHttpClientFactory(SmartScadUnsafeOkHttpClientFactory)
    ApplicationLifecycleDispatcher.onApplicationCreate(this)
  }

  override fun onConfigurationChanged(newConfig: Configuration) {
    super.onConfigurationChanged(newConfig)
    ApplicationLifecycleDispatcher.onConfigurationChanged(this, newConfig)
  }
}
